[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dbms"
version = "1.0.0"
dependencies = [
  "logging",
]

[tool.setuptools.packages]
find = {}

[tool.pytest.ini_options]
pythonpath = "dbms"

[project.scripts]
db = "dbms.cli.scripts:repl"
